version: '3.8'

services:
  backend:
    image: zelalemzola/sunday-backend:latest
    build:
      context: ./church-server
    container_name: church-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://zelalemfiseha26_db_user:zolazola@ac-cxhsxhf-shard-00-00.pj2hwsn.mongodb.net:27017,ac-cxhsxhf-shard-00-01.pj2hwsn.mongodb.net:27017,ac-cxhsxhf-shard-00-02.pj2hwsn.mongodb.net:27017/church_db?ssl=true&replicaSet=atlas-565zob-shard-0&authSource=admin&appName=workconnect
      - JWT_SECRET=7f8a9b2c4d6e8f0a1b3c5d7e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8r
      - REFRESH_TOKEN_SECRET=7f8a9b2c4d6e8f0a1b3c5d7e9f1a2b3c4d5e6f7a8b9c0diidjvbd4545
      - CLOUDINARY_CLOUD_NAME=dh6o29yiy
      - CLOUDINARY_API_KEY=912664363111828
      - CLOUDINARY_API_SECRET=9pWv9HnHrEtQIVJofd2f_zVgp0s

  frontend:
    image: zelalemzola/sunday-frontend:latest
    build:
      context: ./church-system
    container_name: church-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
