apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sunday-school-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/zele26/Sunday-school-management-system.git'
    targetRevision: HEAD
    path: k8s-manifests/frontend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: church-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
